### ISSUE TITLE
purpose dedicated window not working

### ISSUE THREAD

**Issue by et2010** [bmag/emacs-purpose#102]
I use following layout while exporting to latex beamer from org:
![purpose-dedicated-window-not-working-1](https://cloud.githubusercontent.com/assets/11584902/19711822/3697afe8-9b6b-11e6-8c89-abb40a74e737.PNG)

After the "Org Export Process" buffer was killed:
![purpose-dedicated-window-not-working-2](https://cloud.githubusercontent.com/assets/11584902/19711869/9887c652-9b6b-11e6-8e46-ddfb6d1e7bd7.PNG)

As you can see, the purpose of bottom left window was changed (original purpose was `info!`, now it's `org!`). 

OS:
archlinux
emacs 24.5
spacemacs 0.200.3 @develop branch with window-purpose layer

**Comment by bmag** [comment]
You can fix it by enabling the kill extension. It's disabled by default because it can slow down some Emacs operations. To enable in Spacemacs, add to `user-config`:
```elisp
(purpose-x-kill-setup)
```
To enable in regular Emacs configuration, add to init file:
```elisp
(require 'window-purpose-x)
(purpose-x-kill-setup)
```
