### ISSUE TITLE
The default purpose for buffers visiting files should be `edit`, not `general`

### ISSUE THREAD

**Issue by deb0ch** [bmag/emacs-purpose#113]
I was adding various major modes / filename regexes to have the right purpose when editing xml files, Dockerfiles, Jenkinsfiles and whatnot and something struck me:

*all* buffers visiting a file are for doing some kind of edition, so every buffer visiting a file should have the `edit` purpose, right ?

We could just check the result of `buffer-file-name` before checking all the major-mode and regex rules, to set the default to `edit` instead of `general` for buffers visiting files.

Because I don't think it is doable or reasonable to keep track of *all possible* name regex and major mode of buffers that should be in `edit` purpose, right ?

I don't mind implementing it, if you confirm me first that such a feature makes sense 👷

**Comment by bmag** [comment]
There was a similar report to Spacemacs, actually: https://github.com/syl20bnr/spacemacs/issues/8238

The idea makes sense. If you're willing to implement it, I'll merge it. (as long as the code is fine)

**Comment by deb0ch** [comment]
Ok great, I'll get to it whenever I have a few coding hours :thumbsup::sparkles:

**Comment by bmag** [comment]
Thanks. Don't forget to include tests. I think these would be enough:
- opening a file (`find-file`) that doesn't have a configured purpose should default to `edit`
- opening a file that has configured purpose should use that purpose

**Comment by deb0ch** [comment]
Yep, for sure I will 👍 ✨ 

It was simpler than expected, I already implemented the feature.

Implementing the test might be a bit harder, I'm really not familiar with `ert` or automated testing in general 😕 

Any advice ?

In the meantime I'm opening a PR with the current implementation, to have a first review.

**Comment by deb0ch** [comment]
Implemented the tests, but couldn't test them.

See #114 , I have to go now ! :shipit:

**Comment by deb0ch** [comment]
All clean and ready now :thumbsup::sparkles:

**Comment by bmag** [comment]
Thanks, commented on PR. About running the tests, it's quite simple:
- install Cask (https://github.com/cask/cask, http://cask.readthedocs.io/en/latest/guide/installation.html)
- from window-purpose's directory:
```sh
make install
make test
```
Testing for a specific version of Emacs:
```sh
EMACS=/path/to/emacs make install
EMACS=/path/to/emacs make test
```

**Comment by deb0ch** [comment]
I don't know what I was missing but I tried again today and didn't have difficulty to install it after all.

I guess I wasn't thinking clearly because I was in a hurry 😅

**Comment by bmag** [comment]
Fixed :smile:
