### ISSUE TITLE
Purpose mode with ivy-rich

### ISSUE THREAD

**Issue by Davidbrcz** [bmag/emacs-purpose#119]
Hello,

I'm using ivy mode with [ivy-rich](https://github.com/Yevgnen/ivy-rich) to have a nice prompt when changing buffer. Hence, C-x b is bounded to ivy-switch-buffer and ivy-rich performs   some magic to enhance the display:
`(ivy-set-display-transformer 'ivy-switch-buffer 'ivy-rich-switch-buffer-transformer)`

Using the last reply of [this thread ](https://github.com/bmag/emacs-purpose/issues/92) I was able to get an ivy prompt for switching buffer but I really would like to keep an ivy-rich one.

What would be the best way to get a purpose switch with ivy-rich ?

Thanks,
David

**Comment by bmag** [comment]
1. What is `C-x b` really bound to? (Press `C-h k C-x b` to find out)

2. ivy-rich doesn't change any of the actions, so the actions should be the same as `ivy-switch-buffer`, correct? It should generally work with Purpose (but maybe I'm forgetting a small caveat). What exactly is missing?

**Comment by Davidbrcz** [comment]
With purpose-mode disabled `C-x b` is bound to (ivy-switch-buffer) and it looks [like this](https://mrgrizz.xyz/nextcloud/index.php/s/o6KEdHBm4jNsAr7)

With  purpose-mode enable `C-x b` is bound to (purpose-switch-buffer-overload &optional ARG) and it looks [like this ](https://mrgrizz.xyz/nextcloud/index.php/s/tNPa5x76jZ5GYL2)

I also customized `purpose-preferred-prompt` to set it to `vanilla`.

**Comment by bmag** [comment]
Try this:
```elisp
(define-key purpose-mode-map (kbd "C-x b") nil)
```

**Comment by Davidbrcz** [comment]
It works, sorry for the stupid issue ...
