### ISSUE TITLE
Rewrite x-persp extension to use persp mode instead

### ISSUE THREAD

**Issue by wyuenho** [bmag/emacs-purpose#130]
[perspective-el](https://github.com/nex3/perspective-el) is basically a dead project and it doesn't even install on Emacs 26, it's probably best to rewrite the x-persp extension to use it's decendent [persp-mode.el](https://github.com/Bad-ptr/persp-mode.el)

**Comment by bmag** [comment]
You're probably right, but it's such a low priority I doubt I will ever get to it. I'm not sure anyone even uses it...

**Comment by wyuenho** [comment]
I was trying to play with it, and then it went bonkers haha

May be best to remove it? If anyone is interested, he can write the extension as a separate package.

**Comment by bmag** [comment]
I'd rather keep it so it can be an example of how to write extensions. The purpose-related part should be sound. Could add a warning in the relevant `*-setup` function that the extension isn't exactly functional.

**Comment by wyuenho** [comment]
Doesn't an example only require documentation as opposed to actual code? There are plenty of examples in window-purpose-x.el now.

This extension is also causing lots of byte compilation errors

**Comment by wyuenho** [comment]
Looks like perspective-el is back from the dead. I'll close this for now.
