### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by wyuenho** [bmag/emacs-purpose#132]
There hasn't been a whole lot of development here and I keep bumping into memory usage problems and stupid bugs in purpose-x-*. I'm reluctant to submit more PRs when the rest are just sitting here. What's the status of this project? Is there any plan to renew development or transfer the project to someone else?

**Comment by bmag** [comment]
Hi, the project isn't dead, but it is in maintenance mode. In theory it means I respond to issues, fix bugs and merge PRs, but it's not likely that I will write new features (PRs with new features can still be merged). The reason for the inactivity is just that I don't have much free time to work on it, and especially in the past two months I didn't have time almost at all. I should be able to take care of the open issues and PRs in another 2 or 3 weeks, though.

I am contemplating if I should a co-maintainer. I'm leaning towards "yes", but no decision yet. I did have plans for further development of Purpose, and you can still them in a few open issues, but it doesn't seem that I'll get to implement them. A new maintainer maybe could develop them.

The extensions in purpose-x-\* do have a lesser priority than the rest of Purpose, for example the kill extension has a known performance issue that I don't know how to solve. You might be better off writing your own extensions.

**Comment by wyuenho** [comment]
Thanks for getting back to me!

Are you willing to take PRs for the extensions? I know the core is essential but it's only the extensions that make this project incredibly useful for me.

**Comment by bmag** [comment]
Yes, I'll take PRs for extensions as long as they're good.

**Comment by wyuenho** [comment]
How about the couple ones sitting around? :)

**Comment by bmag** [comment]
I'll take care of them too in another 2-3 weeks.
