### ISSUE TITLE
Neotree always opens on the left instead of neo-window-position

### ISSUE THREAD

**Issue by djeis97** [bmag/emacs-purpose#133]
My guess is that the function [here](https://github.com/bmag/emacs-purpose/blob/a302340e183d20baa4445858d321f43449298829/window-purpose-fixes.el#L103) needs the explicit `'left` replaced with `neo-window-position` is all, but I'm not certain.

**Comment by bmag** [comment]
Thanks, should be fixed by https://github.com/bmag/emacs-purpose/commit/2b640955235d0a50dd1e3128612f41d595bc6dc8
