### ISSUE TITLE
purpose-mode hides the magit-log-select buffer

### ISSUE THREAD

**Issue by duianto** [bmag/emacs-purpose#141]
#### Description :octocat:

**Update:**
While writing the issue title, Github suggested this issue:
Question: Configuring Magit Purpose #91

There's a suggestion to call this command:
`(purpose-x-magit-multi-on)`

And that seems to solve the issue described below.

The issue was reported in the Spacemacs gitter chat:
>Markus Bertheau `@mbertheau` Feb 21 03:24
When I do an instant fixup, the diff and the log don't open side-by-side, but the diff opens full-frame. After exiting the diff with q, I am at the log screen where I can select the commit to fixup into. How do I make those appear side-by-side?

source: https://gitter.im/syl20bnr/spacemacs?at=5c6e0bfac776985d8f288c8f

**Question:**
Are there any downsides to calling `(purpose-x-magit-multi-on)` by default in Spacemacs?

It would be a better default, since the Magit commit fixup command expects that one chooses a commit, but currently the diff window has to be closed first.

---

I'll leave the original issue here, it might expand the search terms, if someone else runs into the same issue.

**Original issue:**
When `purpose-mode` is enabled, then the Magit commit edit commands (see below) only shows the 
`magit-diff: <project>` buffer.

When `purpose-mode` is disabled, then both the `magit-diff: <project>` and `magit-log-select: <project>` buffers are shown.

This happens with these five Magit commit (`c`) edit commands:
```
f Fixup    F Instant fixup
s Squash   s Instant Squash
A Augment
```

#### Reproduction guide :beetle:

- Start `Emacs` with `magit` and `window-purpose` installed, and `purpose-mode` enabled.
- Open `magit-status` to a git project.
- Make a change to a file.
- Stage the change `s`.
- Call Commit, Fixup by pressing: `c f`

*Observed behaviour:* :eyes: :broken_heart:

Only the `magit-diff: <project>` buffer is shown.

![emacs_2019-02-22_14-29-01](https://user-images.githubusercontent.com/13420573/53245611-76643980-36ae-11e9-81a0-bbe077648d81.png)

Pressing `q` hides the `magit-diff: <project>` buffer and the `magit-log-select: <project>` buffer is shown.

*Expected behaviour:* :heart: :smile:

Two existing windows are used (or the frame is split into two if there only was one window).
- One window shows the `magit-diff: <project>` buffer.
- Another window shows the  `magit-log-select: <project>` buffer.

![emacs_2019-02-22_14-29-25](https://user-images.githubusercontent.com/13420573/53245619-7c5a1a80-36ae-11e9-86c0-c67e1e3f4a11.png)

#### Notes :notebook:

The expected behavior occurs when `purpose-mode` is disabled. And when Magit is the only installed package.

The `purpose-mode` can be dis/enabled before each time one tries the commit, fixup `cf` command, and `q` also works instead of `C-c C-k` to abort the fixup.

#### System Info :computer:

magit              20190221.1446
window-purpose     20190206.1759
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
Windows 10 Version 1803

**Comment by bmag** [comment]
Thanks for the report. Enabling the purpose-x-magit extension by calling `(purpose-x-magit-multi-on)` is the correct solution, and I am not aware of any particular downsides. Take it with a grain of salt, though, because I am not familiar with *all* of Magit's major modes and commands, so there could be some corner-cases I don't know about. My suggestion would be to enable the extension by default. You can open a PR to Spacemacs, although I'm not focusing on Spacemacs very much right now so I'm not sure when I'll merge it. One of the other collaborators might merge it too.
