### ISSUE TITLE
Sharing buffer types between multiple purposes

### ISSUE THREAD

**Issue by anlsh** [bmag/emacs-purpose#162]
I'd like to achieve the following behaviour with `purpose`

3-window setup

1. Window 1 has no purpose in particular: I'd like to be able to display pretty much anything in it
2. Window 2 is also general purpose BUT is the priority display for automatically-created `major-mode-foo` buffers. So, for instance, if I'm working with Slime and run `M-x slime`, then the `slime-repl` should always show up in Window 2

I also don't want changing the buffer in window 1 to affect the purpose: so even if I manually switch  to the `slime-repl` buffer in Window 1, if I somehow manage to create another `slime-repl` buffer then it should still open in Window 2.

My question is: is this possible, and if so how would I do this? I've spent some time looking at the readme, but it looks like `emacs-purpose` isn't well-suited to expressing this kind of model

**Comment by anlsh** [comment]
I've managed to overlook the wiki. Until I give it it a read-through to try and find a solution there, I'm closing this issue

**Comment by SreenivasVRao** [comment]
Hi, I read through the wiki, but it's still not very clear to me.
I'd like the same window to be used for both magit and terminal. Any tips?

**Comment by bmag** [comment]
@anlsh as you noted, Purpose is not well-suited to a model where you may want to display a buffer with purpose `p1` in window `w2` if there is already a different window `w1` showing a buffer with the same purpose `p1`. Making the `w1` buffer-dedicated (`M-x purpose-toggle-window-buffer-dedicated`) does circumvent the issue, but I don't know if it makes sense in your workflow.

You can hook into the display mechanism by using `purpose-special-action-sequences` variable, and writing custom display functions that meet your needs. Another option is to disable Purpose, and then you can use the regular mechanism of `display-buffer-alist` (you can still use functions from Purpose if you need them, even when `purpose-mode` is disabled).

@SreenivasVRao if you want the same window to be used for both magit and terminal, then I suggest giving them the same purpose (you will need to configure some purposes; I guess you already saw how to do this in the wiki)
