### ISSUE TITLE
Create new windows with respect to layout

### ISSUE THREAD

**Issue by xphoenix** [bmag/emacs-purpose#164]
Is it possible to create new window with respect to layout? 

Something like If user trys to show buffer with purpose "misc" and there is no window for that porpose, look where a such window should be according to layout and create it in appropriate place.

**Comment by wyuenho** [comment]
> look where a such window should be according to layout and create it in appropriate place

Can you elaborate on how you would make this decision?

**Comment by xphoenix** [comment]
Seems it could be done in conjuction with shakle - found issue here from Alexander, trying that way now :)
