### ISSUE TITLE
'Symbol’s value as variable is void: magit-display-buffer-function' when I start spacemacs

### ISSUE THREAD

**Issue by et2010** [bmag/emacs-purpose#173]
I have to put `(require 'magit)` in `window-purpose-x.el` to workaround this.

**Comment by banzr** [comment]
I just started having this issue, too.

**Comment by bmag** [comment]
Thanks for reporting. Likely cause is [this recent commit](https://github.com/bmag/emacs-purpose/commit/4772219eaca499adde543c1b561cc7d9cbbca09c). Requiring magit in the relevant on/off functions should fix the issue.

I'll take care of it later today. For now, you can workaround this in your config by requiring `magit` before `window-purpose-x`.

**Comment by et2010** [comment]
There is a fix on spacemacs' end:

https://github.com/syl20bnr/spacemacs/commit/af0d0e72763c6b441087dfdb96b65020c3c43650
