### ISSUE TITLE
recent change requires magit within window-purpose-x.el

### ISSUE THREAD

**Issue by emacs18** [bmag/emacs-purpose#175]
4772219eaca499adde543c1b561cc7d9cbbca09c was checked in recently which introduced dependence on `magit-display-buffer-function` within `window-purpose-x.el`.
Since this variable is defined in `magit-mode.el`, I think we now must add `(require 'magit-mode)` within `window-purpose-x.el`.

**Comment by wyuenho** [comment]
Already fixed by #174 . Wait for Melpa to rebuild.

**Comment by emacs18** [comment]
Thanks.  I verified that it worked by using `straight.el` and spacemacs.
