### ISSUE TITLE
imenu-list-update-safe is obsolete

### ISSUE THREAD

**Issue by duianto** [bmag/emacs-purpose#185]
The function `imenu-list-update-safe` is used in the function `purpose-x-code1-update-changed` here:
https://github.com/bmag/emacs-purpose/blob/06f727ec1aba07c41cfa397e8f08bca8c29d970d/window-purpose-x.el#L146

But it's defined as obsolete in `imenu-list` here:
https://github.com/bmag/imenu-list/blob/370cabfd21ffcff8247c676be427a1cc9afb234a/imenu-list.el#L717
```elisp
(define-obsolete-function-alias 'imenu-list-update-safe 'imenu-list-update "imenu-list 0.10")
```

**Comment by bmag** [comment]
Thanks, fixed by https://github.com/bmag/emacs-purpose/commit/dc4f8a00a8b0c1cf6242e1bf47f82e08c508a51e
