### ISSUE TITLE
Wiki page

### ISSUE THREAD

**Issue by gamb** [bmag/emacs-purpose#195]
I didn't expect to be able to edit the Wiki directly, intended to open this as a pull request 😅 

Added some advice on integrating with Consult, though I'm sure this can be developed further.

https://github.com/bmag/emacs-purpose/wiki/Integration-With-Other-Packages#consult

**Comment by gamb** [comment]
Also realising in addition, for my purposes, I had to override the `purpose-switch-buffer-overload` i.e.

```elisp
(define-purpose-prefix-overload purpose-switch-buffer-overload (consult-buffer))
```

**Comment by wyuenho** [comment]
Cool, thanks. Feel free to edit the wiki further as you see fit.
