### ISSUE TITLE
Error load this mode

### ISSUE THREAD

**Issue by zijianyue** [bmag/emacs-purpose#35]
Get the latest code ,and set below code in my .emacs file(only these two lines) ,
(require 'purpose)
(purpose-mode)
it reported below error,please check it.
Eager macro-expansion failure: (error "(alist-get key alist) is not a valid place expression")
WIN7 32bit,emacs 24.4

**Comment by bmag** [comment]
Thanks for posting.

alist-get is a new Emacs feature, and Purpose should use it only when it's available. Does this error prevent you from using Purpose?  
I work with two version of Emacs: 24.3 and the master branch. On Emacs 24.3 I also get this error message when Purpose loads, but it doesn't cause any problems when Purpose runs. On master branch I don't get any error, as alist-get exists there.

**Comment by zijianyue** [comment]
Purpose runs well, but can you adapt purpose on 24.4 to avoid that error,thanks!
