### ISSUE TITLE
Make purpose work with helm

### ISSUE THREAD

**Issue by HackerFoo** [bmag/emacs-purpose#36]
Purpose calls `ido-find-file*` instead of the generic `find-file`, so it doesn't work well with helm.

**Comment by bmag** [comment]
Thanks for posting.  Personally I don't use helm, though I should probably give it a try sometime.

Looks like search-deleting "ido-" everywhere in the source code should do the trick.  I'll fix this today or tomorrow.

**Comment by bmag** [comment]
Fixed it.
I'm closing this issue, but please let me know if you run into anymore problems.
