### ISSUE TITLE
Consider renaming to improve find ability of the package

### ISSUE THREAD

**Issue by jasonm23** [bmag/emacs-purpose#39]
it would help people find this package (when no one is posting about it on Reddit or HKN) to give it a less ambiguous name.

Suggestions:

- window-purpose
- window-role

Etc.  

Basically something which addresses the problem people will wanting to solve. ie. Assigning a usage role to a window.

**Comment by bmag** [comment]
You might be right, I'll consider (window-purpose sounds good to me).  
Are there any specific searches that you tried that didn't show Purpose? I see that a google search for "emacs window management" doesn't show Purpose :(

**Comment by jasonm23** [comment]
The point is most of the time people will be looking in package-list-packages so it just makes it easier to use 'window' in the package name.

Purpose is vague enough that people scanning the list will miss it.

If enough cross references exist on the web, sure, a long tail effect will happen and eventually (if the right keywords get indexed.) then google might start to rank Purpose highly...  But what's the point in gambling on that when the package is still new and relatively unknown.

This is the best time to fix it :)
