### ISSUE TITLE
Full integration with Helm

### ISSUE THREAD

**Issue by bmag** [bmag/emacs-purpose#41]
Current integration with Helm is OK, but should be improved. Requires good knowledge of Helm.
1. Find all situations where Purpose causes Helm to work differently than it should.
2. Fix those situations as elegantly as possible.

**Comment by jinnovation** [comment]
As a suggestion, `purpose-set-window-purpose` could be integrated with Helm to select from a list of all currently defined/present/available purposes.

**Comment by bmag** [comment]
That's a good idea. The user interface for that function really isn't very good. The interface should use either IDO or Helm.

On the technical side, you're suggestion should be a seperate issue (I'll create one). The issue on this page (#41) is about fixing all occasions where Purpose interferes with Helm.

**Comment by bmag** [comment]
Integration seems fine now. Not sure if it's something I did, or something that changed in Helm, but I don't spot any problems anymore.
