### ISSUE TITLE
Check integration with popwin

### ISSUE THREAD

**Issue by bmag** [bmag/emacs-purpose#44]
Need to check if Purpose and popwin work together.

**Comment by bmag** [comment]
Turns out that popwin saves and restores the window layout when it create the popup window. The relevant function is `popwin:replicate-window-config`:
1. need to make popwin restore the `purpose-dedicated` window parameter (see [PR](https://github.com/m2ym/popwin-el/pull/121))
2. `popwin:replicate-window-config` uses `switch-to-buffer` or `pop-to-buffer`, so Purpose should be deacitvated when it runs

**Comment by bmag** [comment]
Nothing more to be done on Purpose's side. Info [here](https://github.com/bmag/emacs-purpose/wiki/Integration-With-Other-Packages)

**Comment by ocharles** [comment]
That page says

> Popwin
> status: Pending approval of pull request

But the linked pull request is closed. Is this status out of date?

**Comment by bmag** [comment]
Yes. The maintainer didn't respond for a very long time so I closed it.

**Comment by bmag** [comment]
Thanks, updated the page.
