### ISSUE TITLE
switch-to-buffer broken when its argument is nil

### ISSUE THREAD

**Issue by ilupin** [bmag/emacs-purpose#79]
In the document string of switch-to-buffer:
> If BUFFER-OR-NAME is nil, switch to the buffer returned by `other-buffer'.

However, it fails when purpose mode is turned on.

**Comment by bmag** [comment]
Thanks for the report, I will look into it. Can you describe how it fails?

**Comment by ilupin** [comment]
`(eval (switch-to-buffer nil))` just produces an error "Wrong type argument: stringp, nil".
Normally it should switch to previous buffer.

**Comment by bmag** [comment]
I've found the problem and I'll push a fix later today or tomorrow. In the meantime you can use this advice:
```elisp
(advice-add 'purpose-select-buffer :filter-args
            (lambda (args)
              (cons (window-normalize-buffer-to-switch-to (car args))
                    (cdr args))))
```

**Comment by bmag** [comment]
Fixed in https://github.com/bmag/emacs-purpose/commit/3820ff87df683a1880f5c81427d656e51b0e2865
