### ISSUE TITLE
Unexpected behaviour when using org-edit-src-code

### ISSUE THREAD

**Issue by samis** [bmag/emacs-purpose#89]
I now use a literate init file, so in order to take advantage of aggressive-indent-mode I can use the function org-edit-src-code to open the block of code in a buffer with the correct major mode set. GHowever, while Purpose assigns the correct purpose to this new buffer it does not display it in an expected manner.

For example, if I have a larger window dedicated to the 'edit' purpose and a smaller undedicated window, it will use the latter to display this buffer despite it also having the edit purpose. Shouldn't it display in the dedicated window rather than the undedicated one?

**Comment by bmag** [comment]
Usually the buffer will be displayed in the existing 'edit' window, but not always.

If both windows are same purpose, then one of them is used. Dedication prevents usage for other purpose, but doesn't give priority over undedicated windows of the same purpose.

The window chosen depends on the function used by the underlying code. Assuming the dedicated 'edit' window is selected, the other window doesn't have the 'edit' purpose and isn't dedicated to its purpose, and the code wants to display a new 'edit' buffer:
- If the code uses `pop-to-buffer`, the new buffer should be displayed in the dedicated 'edit' window
- If the code uses `switch-to-buffer-other-window`, the new buffer should be displayed in the non-edit window (and that window will become an 'edit' window as a result).
- If the code uses `pop-to-buffer` or `display-buffer` and provides an `action` argument, that action takes precedence over the usual display rules.

In the case of `org-edit-src-code`, the behaviour can be customized by the variable `org-src-window-setup`. The function `org-src-switch-to-buffer` is responsible for displaying the code buffer.

As you can see below, if `org-src-window-setup` value is `current-window`, `org-src-switch-to-buffer` will display the buffer in the current window (via `pop-to-buffer-same-window`). If the value is `other-window`, it will use `switch-to-buffer-other-window` (not `pop-to-buffer`). For other values the behaviour is a bit more complex. You can set `org-src-window-setup` to `current-window` and see if that suits your workflow.

```elisp
(defun org-src-switch-to-buffer (buffer context)
  (case org-src-window-setup
    (current-window (org-pop-to-buffer-same-window buffer))
    (other-window
     (switch-to-buffer-other-window buffer))
    (other-frame
     (case context
       (exit
	(let ((frame (selected-frame)))
	  (switch-to-buffer-other-frame buffer)
	  (delete-frame frame)))
       (save
	(kill-buffer (current-buffer))
	(org-pop-to-buffer-same-window buffer))
       (t (switch-to-buffer-other-frame buffer))))
    (reorganize-frame
     (when (eq context 'edit) (delete-other-windows))
     (org-switch-to-buffer-other-window buffer)
     (when (eq context 'exit) (delete-other-windows)))
    (switch-invisibly (set-buffer buffer))
    (t
     (message "Invalid value %s for `org-src-window-setup'"
	      org-src-window-setup)
     (org-pop-to-buffer-same-window buffer))))
```

**Comment by samis** [comment]
Unfortunately, it seemed to have no effect. It still opened in the same window as it did with the previous setting.

**Comment by bmag** [comment]
@samis I looked through your config on github (I hope you don't mind) and I saw that you configured org buffers to have an 'org' purpose. This means that org buffers don't have the 'edit' purpose.
If your org window is dedicated to 'org', then purpose-mode prevents it from being used for other purposes such as 'edit', even if you do set `org-src-window-setup` to `current-window`.

You can get around by wrapping `org-src-switch-to-buffer` inside of `without-purpose`, so purpose-mode is temporarily disabled. Here's an example:
```elisp
(defun apply-without-purpose (func &rest args)
  "Temprarily disable purpose-mode while applying FUNC.
FUNC is a function to call, and ARGS are passed as FUNC's arguments.
Can be used as an 'around' advice."
  (without-purpose (apply func args)))

(advice-add #'org-src-switch-to-buffer :around #'apply-without-purpose)
```

Or if you'd rather not use advice, you can define and use custom commands to start and finish editing a source block. For example, where `<the-original-command-you-would-normally-use>` might be `org-edit-special` or `org-edit-src-exit`:
```elisp
(defun start-edit-block ()
  (interactive)
  (without-purpose
    (call-interactively #'<the-original-command-you-would-normally-use>)))

(defun finish-edit-block ()
  (interactive)
  (without-purpose
    (call-interactively #'<the-original-command-you-would-normally-use>)))
```

**Comment by samis** [comment]
Good point. One other thing I may have failed to previously say clearly was this: I don't personally mind it opening in another window - both are fine. What was interesting was that given 2 'edit'-purposed windows it chose the smaller one over the larger one. Wouldn't it make more sense to choose the larger one over the smaller one?

**Comment by bmag** [comment]
> Wouldn't it make more sense to choose the larger one over the smaller one?

Honestly I don't know, it really depends on the situation. I mean, the smaller window isn't useless, so if both windows have the same purpose, it's not easy to know if the buffer should be displayed in the small one or the large one. The proper window may be different depending on the buffer. Moreover, sometimes the correct window for the same buffer can change depending on unknown context...

As far as I understand the window system of Emacs, the solution to this problem is to provide the user with several commands to display a buffer, each with a slightly different meaning as to where to display the buffer. Additionally, there is `display-buffer-alist` and a few other variables to customize `display-buffer` on a per-buffer or a per-buffer-name-pattern basis. So if there are two windows, Emacs will choose based on the command used and `display-buffer`'s rules. Purpose changes the rules a bit, but it still relies on the command used.

If you have any suggestions or ideas, feel free bring them up :wink:
