### ISSUE TITLE
Question: Configuring Magit Purpose

### ISSUE THREAD

**Issue by nixmaniack** [bmag/emacs-purpose#91]
I'm been using `window-purpose` layer of Spacemacs since long time and haven't needed to configure it. Thanks for that. 

Now I've been facing one issue, where I have two windows, one with magit-log buffer and other with code. How do I go about configuring `emacs-purpose` that if I open some commit log, it should open in other-window and not the current magit-log buffer window?

**Comment by bmag** [comment]
window-purpose has an extension for magit that isn't used in the layer. Try adding `purpose-x-magit-multi-on` to your config.

The magit-multi extension is supposed to give a different purpose for each magit-related major mode. However, it seems that I didn't update it for the latest magit. The extension currently defines purposes only for these modes:
- magit-diff-mode
- magit-status-mode
- magit-log-mode
- magit-commit-mode
- magit-cherry-mode
- magit-branch-manager-mode
- magit-process-mode
- magit-reflog-mode
- magit-wazzup-mode

But running ag on magit's directory reveals more major modes:
- magit-status-mode
- magit-refs-mode
- magit-merge-preview-mode
- magit-log-mode
- magit-log-select-mode
- magit-cherry-mode
- magit-reflog-mode
- magit-mode
- git-rebase-mode
- magit-diff-mode
- magit-revision-mode
- magit-stashes-mode
- magit-stash-mode
- magit-process-mode
I don't think it will cause any problems for you, but if it does ping me.

**Comment by nixmaniack** [comment]
Awesome! It was already there and I waited long to ask for it! After enabling `purpose-x-magit-multi-on` I'm quite happy, haven't needed to add other major modes yet, will add them if required.

Thank you.
